import { ServerPlan } from "@/schemas/serverPlan.schema";

export function renderServerProperties(plan: ServerPlan, motd: string): string {
  // Only known, safe keys — never write arbitrary user-supplied key/value
  // pairs straight into server.properties.
  const lines: Record<string, string | number | boolean> = {
    "server-name": plan.server.name,
    motd,
    gamemode: plan.server.gamemode,
    difficulty: plan.server.difficulty,
    pvp: plan.server.pvp,
    "max-players": plan.server.maxPlayers,
    "spawn-protection": plan.server.spawnProtection,
    "view-distance": plan.server.viewDistance,
    "simulation-distance": plan.server.simulationDistance,
    "online-mode": true,
    "enable-command-block": false,
    "allow-flight": plan.serverType === "minigames" || plan.serverType === "creative",
  };
  return Object.entries(lines)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n") + "\n";
}

export function renderEula(): string {
  return (
    "# By changing the setting below to TRUE you are indicating your agreement to our EULA\n" +
    "# https://aka.ms/MinecraftEULA\n" +
    `#${new Date().toUTCString()}\n` +
    "eula=false\n" // The end user must explicitly accept this themselves — never auto-set to true.
  );
}

export function renderStartScriptSh(jarName: string, ramMb: number): string {
  return `#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
java -Xms${ramMb}M -Xmx${ramMb}M -jar ${jarName} nogui
`;
}

export function renderStartScriptBat(jarName: string, ramMb: number): string {
  return `@echo off
cd /d "%~dp0"
java -Xms${ramMb}M -Xmx${ramMb}M -jar ${jarName} nogui
pause
`;
}

export function renderReadme(plan: ServerPlan, pluginNames: string[], resolvedVersion: string): string {
  const branding = plan.branding;
  const brandingLines = [
    branding.discordUrl ? `Discord: ${branding.discordUrl}` : null,
    branding.twitchUrl ? `Twitch: ${branding.twitchUrl}` : null,
    branding.websiteUrl ? `Website: ${branding.websiteUrl}` : null,
    branding.webshopUrl ? `Webshop: ${branding.webshopUrl}` : null,
  ].filter(Boolean);

  return `# ${plan.server.name}

Minecraft: ${plan.minecraft.version} Java Edition
Server software: ${plan.software.type} (${resolvedVersion})
Server type: ${plan.serverType}

## Plugins
${pluginNames.map((n) => `- ${n}`).join("\n") || "(none)"}

${brandingLines.length ? "## Links\n" + brandingLines.join("\n") + "\n" : ""}
## Installation
1. Install a Java version compatible with Minecraft ${plan.minecraft.version}.
2. Extract this package.
3. Open eula.txt and change eula=false to eula=true if you agree to Mojang's EULA.
4. Run start.sh (Linux/macOS) or start.bat (Windows).
5. Review server.properties and plugin configs before opening to the public.

Generated by AI Minecraft Server Pack Builder.
`;
}

export function renderLicenses(entries: { name: string; license: string | null; officialUrl: string | null }[]): string {
  return (
    "This package bundles third-party plugins/mods. Their licenses apply independently of this tool.\n\n" +
    entries
      .map((e) => `- ${e.name}: ${e.license ?? "unknown license — verify before redistribution"}${e.officialUrl ? ` (${e.officialUrl})` : ""}`)
      .join("\n") +
    "\n"
  );
}
